spring:
  profiles:
    active:
      - "@profileActive@"
#  datasource:
#   url: jdbc:h2:mem:dbtest
#   username: sa
#   password: pass
#  
#  jpa:
#   show-sql: true
#   database-platform: org.hibernate.dialect.H2Dialect
#   defer-datasource-initialization: true
#   hibernate:
#    ddl-auto: validate
#    
#  h2:
#    console:
#      enabled: true      
##     
      
#  datasource:
#    url: ${DB_URL_JAVALIN}
#    username: ${DB_USER}
#    password: ${DB_PASS}
#  jpa:
#    show-sql: true
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: validate
#    properties:
#      hibernate:
#        generate_statistics: true
management:
  endpoints:
      web:
        exposure:
          include: health,metrics,prometheus
  metrics:
    distribution:
      percentiles-histogram.http.server.requests: true
      percentiles.http.server.requests: 0.5, 0.9, 0.95, 0.99, 0.999         
          
          
          
          