apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-promtail-config
  namespace: k8s-cluster
data:
  promtail.yml: |-
      server:
        http_listen_port: 9080
        grpc_listen_port: 0
      positions:
        filename: /tmp/positions.yaml
      clients:
        - url: http://loki:3100/loki/api/v1/push
      scrape_configs:
        - job_name: system
          static_configs:
            - targets:
                - localhost
              labels:
                job: project2
                __path__: /var/log/*.log
                namespace: teamww
          pipeline_stages:
            - json:
                expressions:
                  level: level
            - labels:
                level:
